export const ADD_EVENT = 'ADD_EVENT'
export const SET_EVENTS = 'SET_EVENTS'
export const SET_EVENTS_VERSION = 'SET_EVENTS_VERSION'
export const CLEAR_EVENTS_TRANSACTIONS = 'CLEAR_EVENTS_TRANSACTIONS'
